export const authConstants = {
  LOGIN_CONFIRM_SUCCESS: "LOGIN_CONFIRM_SUCCESS",
  LOGIN_CONFIRM_FAIL: "LOGIN_CONFIRM_FAIL",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL",
  SIGNUP_LOGIN_SUCCESS: "SIGNUP_LOGIN_SUCCESS",
  SIGNUP_LOGIN_FAIL: "SIGNUP_LOGIN_FAIL",
};

export const alertConstants = {
  ALERT_SET: "ALERT_SET",
  ALERT_REMOVE: "ALERT_REMOVE",
};

export const productConstants = {
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAIL: "GET_ALL_PRODUCTS_FAIL",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAIL: "CREATE_PRODUCT_FAIL",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAIL: "UPDATE_PRODUCT_FAIL",
  GET_SINGLE_PRODUCT_SUCCESS: "GET_SINGLE_PRODUCT_SUCCESS",
  GET_SINGLE_PRODUCT_FAIL: "GET_SINGLE_PRODUCT_FAIL",
  DELETE_SINGEL_PRODUCT_SUCCESS: "DELETE_SINGEL_PRODUCT_SUCCESS",
  DELETE_SINGEL_PRODUCT_FAIL: "DELETE_SINGEL_PRODUCT_FAIL",
};

export const commentConstants = {
  GET_NOT_APPROVED_COMMENTS_SUCCESS: "GET_NOT_APPROVED_COMMENTS_SUCCESS",
  GET_NOT_APPROVED_COMMENTS_FAIL: "GET_NOT_APPROVED_COMMENTS_FAIL",
  UPDATE_NOT_APPROVED_COMMENTS_SUCCESS: "UPDATE_NOT_APPROVED_COMMENTS_SUCCESS",
  UPDATE_NOT_APPROVED_COMMENTS_FAIL: "UPDATE_NOT_APPROVED_COMMENTS_FAIL",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAIL: "DELETE_COMMENT_FAIL",
};
